cc_library(
	name = "ensemble_classes",
	srcs = ["Ensemble.cpp","jEnsemble.cpp","vEnsemble.cpp"],
	hdrs = ["Ensemble.hpp","jEnsemble.hpp","vEnsemble.hpp","Constants.hpp"],
	visibility = ["//src:__pkg__"],
)

cc_library(
	name = "Molecules_classes",
	srcs = ["Molecules.cpp"],
	hdrs = ["Molecules.hpp"],
	visibility = ["//src:__pkg__"],
)

cc_library(
	name = "propagator_classes",
	srcs = ["Propagator.cpp"],
	hdrs = ["Propagator.hpp"],
	visibility = ["//src:__pkg__"],
)

cc_library(
	name = "pulse_classes",
	srcs = ["PulseFreq.cpp","PulseTime.cpp"],
	hdrs = ["PulseFreq.hpp","PulseTime.hpp"],
	visibility = ["//src:__pkg__"],
)

